from django.urls import path,include
from .views import (
    PersonnageListView,
    PersonnageDetailView,
    PersonnageCreateView,
    PersonnageUpdateView,
    PersonnageDeleteView,
      scenarioListView,
    scenarioDetailView,
    scenarioCreateView,
    scenarioUpdateView,
    scenarioDeleteView,
        ProjetListView,
    ProjetDetailView,
    ProjetCreateView,
    ProjetUpdateView,
    ProjetDeleteView,
    EffetSonoreVisuellesListView,
    EffetSonoreVisuellesDetailView,
    EffetSonoreVisuellesCreateView,
    EffetSonoreVisuellesUpdateView,
    EffetSonoreVisuellesDeleteView,
    analyze_sentiment,
    sentiment_analysis_view,
    chat,  # Import the chat view
    ask_question, 
    like_personnage,
    generate_image_ajax,
    film_create,
    film_list,
    film_detail,
    film_update,
    film_delete,
    add_comment,
    delete_comment
)

app_name = 'module'

urlpatterns = [
    path('personnages/', PersonnageListView.as_view(), name='personnage_list'),
    path('personnages/<int:pk>/', PersonnageDetailView.as_view(), name='personnage_detail'),  # Correction ici
    path('personnages/nouveau/', PersonnageCreateView.as_view(), name='personnage_create'),
    path('personnages/<int:pk>/modifier/', PersonnageUpdateView.as_view(), name='personnage_update'),
    path('personnages/<int:pk>/supprimer/', PersonnageDeleteView.as_view(), name='personnage_delete'),
    path('personnages/<int:pk>/like/', like_personnage, name='like_personnage'),
    path('personnage/<int:personnage_id>/add_comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
    path('scenario/', scenarioListView.as_view(), name='scenario_list'),
    path('scenario/<int:pk>/', scenarioDetailView.as_view(), name='scenario_detail'),
    path('scenario/nouveau/', scenarioCreateView.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/modifier/', scenarioUpdateView.as_view(), name='scenario_update'),
    path('scenario/<int:pk>/supprimer/', scenarioDeleteView.as_view(), name='scenario_delete'),
   path('chat/', chat, name='chat_bot'),  # URL for the chatbot interface
    path('ask/', ask_question, name='ask_question'), 
     path('generate-image/', generate_image_ajax, name='generate_image_ajax'),
       path('film/', film_list, name='film_list'),
    path('film/new/', film_create, name='film_create'),
    path('film/<int:pk>/', film_detail, name='film_detail'),
    path('film/<int:pk>/edit/', film_update, name='film_update'),
    path('film/<int:pk>/delete/',film_delete, name='film_delete'),
    path('projets/', ProjetListView.as_view(), name='projet_list'),
    path('projets/<int:pk>/', ProjetDetailView.as_view(), name='projet_detail'),
    path('projets/create/', ProjetCreateView.as_view(), name='projet_create'),
    path('projets/update/<int:pk>/', ProjetUpdateView.as_view(), name='projet_update'),
    path('projets/delete/<int:pk>/', ProjetDeleteView.as_view(), name='projet_delete'),
     path('effetsonorevisuelles/', EffetSonoreVisuellesListView.as_view(), name='effetsonorevisuelles_list'),
    path('effetsonorevisuelles/<int:pk>/', EffetSonoreVisuellesDetailView.as_view(), name='effetsonorevisuelles_detail'),
    path('effetsonorevisuelles/create/', EffetSonoreVisuellesCreateView.as_view(), name='effetsonorevisuelles_create'),
    path('effetsonorevisuelles/update/<int:pk>/', EffetSonoreVisuellesUpdateView.as_view(), name='effetsonorevisuelles_update'),
    path('effetsonorevisuelles/delete/<int:pk>/', EffetSonoreVisuellesDeleteView.as_view(), name='effetsonorevisuelles_delete'),
    path('sentimentBot/sentiment-analysis/', sentiment_analysis_view, name='sentiment_analysis'),
    
]