# Generated by Django 4.1 on 2024-10-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('acteur', models.CharField(max_length=255)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
