# Generated by Django 4.1 on 2024-10-11 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0003_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnage',
            name='acteur',
        ),
        migrations.AddField(
            model_name='personnage',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_personnages', to=settings.AUTH_USER_MODEL),
        ),
    ]
