# Generated by Django 4.1 on 2024-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_remove_personnage_acteur_personnage_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('realisateur', models.CharField(max_length=100)),
                ('annee_sortie', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
