# Generated by Django 4.1 on 2024-10-26 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0005_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnage',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='personnage',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nom du personnage'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='film.personnage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
