# Generated by Django 4.1 on 2024-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffetSonoreVisuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
