# Generated by Django 4.1 on 2024-10-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_effetsonorevisuelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='effetsonorevisuelles',
            name='projet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='effets', to='film.projet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effetsonorevisuelles',
            name='typeEffet',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Sound', 'Sound')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
